In [1]:
import pandas as pd

In [5]:
df = pd.read_excel(r'C:\Users\Baby Pal\Downloads\sales_raw_500.xlsx')
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001 2023-01-13    Rohit  South   Mobile  23289  19118
1      1002 2023-10-07     Aman   West   Laptop   8905   5593
2      1003 2023-11-05    Rahul  South  Monitor  59987  39959
3      1004 2024-02-19    Rahul  South  Printer  49597  33892
4      1005 2024-01-26   Anjali  North   Laptop  54797  34468

In [8]:
#duplicate remove
df =df.drop_duplicates()
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [9]:
#black data fill
df['Order_Date'] = pd.to_datetime(df['Order_Date'],errors='coerce')
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [10]:
df=df.dropna(subset=['Order_Date'])
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [11]:
df['Profit'] = df['Sales']-df['Cost']
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost  Profit
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118    4171
1        1002 2023-10-07     Aman   West   Laptop   8905   5593    3312
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959   20028
3        1004 2024-02-19    Rahul  South  Printer  49597  33892   15705
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468   20329
..        ...        ...      ...    ...      ...    ...    ...     ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931    5778
495      1496 2023-04-24    Kiran  North  Printer  23434  16388    7046
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970   13037
497      1498 2023-05-08     Aman   East   Tablet  19160  15636    3524
499      1500 2023-10-07    Vikas  North  Printer  34567  22426   12141

[482 rows x 8 columns]

In [12]:
df['Month'] = df['Order_Date'].dt.month
df['Year'] = df['Order_Date'].dt.year
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Month,Year
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,1,2023
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,10,2023
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,11,2023
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2,2024
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,1,2024
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,10,2023
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,4,2023
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,6,2023
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,5,2023
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,10,2023

In [13]:
df.to_csv('sales_clean.csv',index = False)

In [14]:
from sqlalchemy import create_engine

In [15]:
df = pd.read_csv('sales_clean.csv')

In [22]:

engine = create_engine('mysql+pymysql://root:root@localhost:3306/salesdb')

In [23]:


df.to_sql(name='sales_data', con=engine, if_exists='replace', index=False)

482

In [19]:
df2 = pd.read_sql("SELECT * FROM sales_data", con=engine)
df2.head()

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Month,Year
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,1,2023
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,10,2023
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,11,2023
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2,2024
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,1,2024